on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2.5.0
        with:
          ref: ${{ github.head_ref }}
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      - name: Build and push Docker image to ECR
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: public.ecr.aws/h2a8c7h3/demo-repo:latest
          github-token: ${{ secrets.GITHUB_TOKEN }}
