on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

stages:
  - build
  - deploy

build:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  script:
    - docker build -t my-image:latest .
    - $(aws ecr get-login --no-include-email --region us-east-2)
    - docker tag my-image:latest public.ecr.aws/h2a8c7h3/demo-repo:latest
    - docker push public.ecr.aws/h2a8c7h3/demo-repo:latest

deploy:
  stage: deploy
  image: python:3.9
  script:
    - echo "Deploying my-image:latest to production..."
    
    jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build Docker image
        run: docker build -t my-image:latest .
      - name: Push Docker image
        run: docker push my-image:latest

