on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build Docker image
        run: docker build -t my-image:latest .
      - name: Push Docker image
        run: |
          $(aws ecr get-login --no-include-email --region us-east-2)
          docker tag my-image:latest public.ecr.aws/h2a8c7h3/demo-repo:latest
          docker push public.ecr.aws/h2a8c7h3/demo-repo:latest

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to production
        run: echo "Deploying my-image:latest to production..."
        # Add deployment commands here
