on:
  push:
    branches:
      - master

stages:
  - build-and-push

build-and-push:
  stage: build-and-push
  image: docker:latest
  services:
    - docker:dind
  variables:
    AWS_REGION: us-east-2
    ECR_REPOSITORY_URI: public.ecr.aws/h2a8c7h3/demo-repo
  before_script:
    - echo "Logging in to Amazon ECR..."
    - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $ECR_REPOSITORY_URI
  script:
    - echo "Building Docker image..."
    - docker build -t $ECR_REPOSITORY_URI:$CI_COMMIT_SHORT_SHA .
    - echo "Pushing Docker image to Amazon ECR..."
    - docker push $ECR_REPOSITORY_URI:$CI_COMMIT_SHORT_SHA
