name: Build and Push Docker Image

on:
  push:
    branches:
      - main

env:
  ECR_REGION: us-east-2
  ECR_REGISTRY: public.ecr.aws/h2a8c7h3/demo-repo
  DOCKER_IMAGE_TAG: latest

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Login to AWS ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
        with:
          region: ${{ env.ECR_REGION }}
      
      - name: Build Docker Image
        id: build-image
        run: |
          docker build -t $ECR_REGISTRY:$DOCKER_IMAGE_TAG .
          echo "::set-output name=image_uri::$ECR_REGISTRY:$DOCKER_IMAGE_TAG"

      - name: Push Docker Image to ECR
        id: push-image
        uses: aws-actions/amazon-ecr-push-image@v1
        with:
          region: ${{ env.ECR_REGION }}
          registry: ${{ env.ECR_REGISTRY }}
          image: ${{ steps.build-image.outputs.image_uri }}

      - name: Cleanup
        run: |
          docker logout $ECR_REGISTRY
